# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Get_chistat <- function(X, Sigma, B, m_select, is_Sigma_identity) {
    .Call(`_EnsembleTests_Get_chistat`, X, Sigma, B, m_select, is_Sigma_identity)
}

